# Site settings
title: 'Beta Lab'
title_zh: 'Beta Lab'
subtitle: 'Bigdata Research Center of UESTC'
subtitle_zh: '电子科技大学大数据研究中心'

email: jiaoxinshan@std.uestc.edu.cn
# description: 'Advanced AI Research Laboratory at University'
# description_zh: '大学人工智能研究实验室'
baseurl: ''
url: 'https://Evian-code.github.io'

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:categories/:year/:month/:day/:title/

# Collections
collections:
  posts:
    output: true
    permalink: /:categories/:year/:month/:day/:title/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude files
exclude:
  - vendor
  - Gemfile
  - Gemfile.lock
  - README.md

# Language settings
languages: ['zh', 'en']
default_lang: 'zh'

lab:
  name: Beta Lab
  name_zh: Beta Lab
  address: 成都市高新区（西区）西源大道2006号, 电子科技大学清水河校区创新中心B318
  phone: +86 17394988380
  email: jiaoxinshan@std.uestc.edu.cn
  about_en: >
    We are a research group focusing on complexity science and education science.
  about_zh: >
    我们是一个专注于复杂性科学和教育科学的研究团队。
description: Research in complexity science, education science, and related fields.
description_zh: 从事复杂性科学,教育科学等方向研究。

social:
  Website: https://evian-code.github.io/
